# CRE config for WeatherShield

networks:
  arbitrum-sepolia:
    rpc: "https://sepolia-rollup.arbitrum.io/rpc"
    chainId: 421614

contracts:
  weathershield:
    address: "0x0988119B3526C21129E0254f5E8bd995Bed51F6D"
    network: arbitrum-sepolia

workflows:
  - ./cre-workflows/weather-monitor.yaml
